name: Update README
on:
  schedule:
    - cron: '*/3 * * * *' # Runs every 30 minutes
jobs:
  build:
    runs-on: ubuntu-latest
    name: Update README with recent activity
    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_README }}
